# Generated by Django 5.2.12 on 2026-03-26 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GalleryImage',
            new_name='Products',
        ),
    ]
