# Generated by Django 5.2.12 on 2026-03-25 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
