# Generated by Django 5.2.12 on 2026-03-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
